network:
  version: 2
  ethernets:
    eth0:
      renderer: NetworkManager
      match: {}
      addresses:
      - "192.168.233.172/24"
      nameservers:
        addresses:
        - 8.8.8.8
        - 1.1.1.1
      routes:
      - to: "0.0.0.0/0"
        via: "192.168.233.1"
      networkmanager:
        uuid: "75a1216a-9d1a-30cd-8aca-ace5526ec021"
        name: "netplan-eth0"
        passthrough:
          proxy._: ""
